version: "3"

services:
  mariabdb:
    image: mariadb:latest
    container_name: taskManager_mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=taskManager
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=application
      - MYSQL_PASSWORD=1234
    volumes:
      - ./init:/docker-entrypoint-initdb.d
